data:
  train_dir: "C:\\HyperObjectData\\data\\train"
  val_dir: "C:\\HyperObjectData\\data\\test-public"
  patch_size: 256
  batch_size: 8
  num_workers: 4

model:
  name: unet
  in_channels: 1
  out_channels: 61
  base_filters: 32

train:
  epochs: 100
  lr: 1e-4
  weight_decay: 1e-6
  save_dir: "C:\\HyperObjectData\\checkpoints"
  device: cuda
